//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DartHostingExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Dart.DartAppResource> AddDartApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string entrypoint = "bin/main.dart") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithAppArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, params object[] args)
            where T : Dart.DartAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithDartDefine<T>(this ApplicationModel.IResourceBuilder<T> builder, string key, string value)
            where T : Dart.DartAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithPubGet<T>(this ApplicationModel.IResourceBuilder<T> builder, bool install = true)
            where T : Dart.DartAppResource { throw null; }
    }
}

namespace Aspire.Hosting.Dart
{
    [AspireExport(ExposeProperties = true)]
    public partial class DartAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public DartAppResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }
}