// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable ASPIREDOCKERFILEBUILDER001

using System.Text.RegularExpressions;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Aspire.Hosting.Elixir;

/// <summary>
/// Generates the Dockerfile that <c>aspire publish</c> writes for an Elixir application or a Mix release.
/// </summary>
/// <remarks>
/// <para>
/// An application built from source gets two stages. The build stage compiles the project with Mix and
/// runs <c>mix release</c>. The runtime stage carries only the release directory, so the image holds no
/// compiler, no source, and no Hex cache.
/// </para>
/// <para>
/// A release that Mix already built gets one stage, because there is nothing left to compile.
/// </para>
/// </remarks>
internal static partial class ElixirDockerfileGenerator
{
    /// <summary>The working directory in both stages.</summary>
    private const string ContainerAppDirectory = "/app";

    /// <summary>The account that runs the release. The image must not run the release as root.</summary>
    private const string NonRootUser = "app";

    /// <summary>
    /// The Debian release that the runtime image uses when the caller supplies a plain Debian image.
    /// </summary>
    /// <remarks>
    /// The default images below are not Debian images, so this constant only documents the release that
    /// the generated locale commands expect. See the remarks on <see cref="BuildImage"/>.
    /// </remarks>
    internal const string DebianCodename = "bookworm";

    // Without these rules `COPY . .` uploads the local build output and the fetched dependencies to the
    // daemon. Both are large, and both are rebuilt inside the image, so both must stay out of the context.
    // See https://docs.docker.com/build/concepts/context/#dockerignore-files.
    private const string DefaultBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to take over these rules.
        _build
        deps
        .elixir_ls
        .lexical
        node_modules
        **/node_modules
        .git
        .gitignore
        .DS_Store
        .env
        .env.*
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    // A release directory holds only files that the image needs, so nothing about the build tree applies
    // here. Only the files that a checkout adds are removed.
    private const string DefaultReleaseBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to take over these rules.
        .git
        .gitignore
        .DS_Store
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    /// <summary>
    /// Builds the default build-stage image reference.
    /// </summary>
    /// <remarks>
    /// The official <c>elixir</c> image is the only published Elixir image with a stable tag. Every
    /// <c>hexpm/elixir</c> tag carries a Debian snapshot date and an exact OTP patch version from the
    /// Hex build matrix, and neither value can be derived from <c>.tool-versions</c> or <c>mix.exs</c>.
    /// The official image takes the OTP major version only, so the detected versions always produce a
    /// tag that exists. Use <c>WithDockerfileBaseImage</c> to select a different image.
    /// </remarks>
    internal static string BuildImage(string elixirVersion, string otpMajorVersion)
        => $"docker.io/library/elixir:{elixirVersion}-otp-{otpMajorVersion}-slim";

    /// <summary>
    /// Builds the default runtime-stage image reference.
    /// </summary>
    /// <remarks>
    /// The official <c>elixir</c> image is built from <c>erlang:&lt;major&gt;-slim</c>, so this image is
    /// the exact base of the build stage. That removes the class of failure where the release, which
    /// carries the Erlang runtime system that the build stage compiled, meets a different C library in
    /// the runtime stage. It also means the image already holds OpenSSL, ncurses, and the C++ runtime.
    /// </remarks>
    internal static string RuntimeImage(string otpMajorVersion)
        => $"docker.io/library/erlang:{otpMajorVersion}-slim";

    /// <summary>
    /// Writes the two-stage Dockerfile for an application that Mix builds from source.
    /// </summary>
    /// <param name="appDirectory">The directory that holds <c>mix.exs</c>. It is also the build context.</param>
    /// <param name="isPhoenix">
    /// <see langword="true"/> for a Phoenix application. A Phoenix application builds its assets and
    /// starts its endpoint from the release.
    /// </param>
    /// <param name="context">The callback context that supplies the Dockerfile builder.</param>
    public static void WriteApplication(string appDirectory, bool isPhoenix, DockerfileBuilderCallbackContext context)
    {
        var logger = context.Services.GetService<ILogger<ElixirAppResource>>();
        var versions = ElixirVersionDetector.Detect(appDirectory);
        var otpMajor = MajorVersion(versions.OtpVersion);

        // ctx.Resource is the container resource that PublishAsDockerFile substitutes in. It shares the
        // annotation collection of the Elixir resource, so annotations that the developer applied to the
        // Elixir resource are visible here.
        context.Resource.TryGetLastAnnotation<DockerfileBaseImageAnnotation>(out var baseImageAnnotation);
        var buildImage = baseImageAnnotation?.BuildImage ?? BuildImage(versions.ElixirVersion, otpMajor);
        var runtimeImage = baseImageAnnotation?.RuntimeImage ?? RuntimeImage(otpMajor);

        var releaseName = ResolveReleaseName(context.Resource, appDirectory);

        WriteBuildContextIgnore(appDirectory, DefaultBuildContextIgnoreContent, context);

        // Phoenix builds its assets from the `assets` directory. A project without that directory has no
        // asset pipeline, so `mix assets.deploy` would fail.
        var hasAssets = isPhoenix && Directory.Exists(Path.Combine(appDirectory, "assets"));
        var hasAssetPackages = hasAssets && File.Exists(Path.Combine(appDirectory, "assets", "package.json"));

        var build = context.Builder.From(buildImage, "build");

        // Native dependencies compile with make and a C toolchain, and Hex fetches some packages over
        // Git. The certificates matter most: the official images purge ca-certificates after they build
        // the toolchain, so `mix local.hex` and `mix deps.get` cannot verify builds.hex.pm without them.
        var buildPackages = hasAssetPackages
            ? "build-essential git ca-certificates nodejs npm"
            : "build-essential git ca-certificates";

        if (IsAlpine(buildImage))
        {
            var alpinePackages = hasAssetPackages
                ? "build-base git ca-certificates nodejs npm"
                : "build-base git ca-certificates";
            build.Run($"apk add --no-cache {alpinePackages}");
        }
        else
        {
            // `apt-get clean` and the list removal keep the layer small.
            build.Run($"apt-get update -y && apt-get install -y {buildPackages} && apt-get clean && rm -f /var/lib/apt/lists/*_*");
        }

        build
            .WorkDir(ContainerAppDirectory)
            .Run("mix local.hex --force && mix local.rebar --force")
            .Env("MIX_ENV", "prod");

        // The manifest, the lock file, and the configuration change less often than the source, so they
        // are copied first. That keeps the dependency layer in the cache across source edits.
        if (File.Exists(Path.Combine(appDirectory, "mix.exs")))
        {
            build.Copy("mix.exs", "./");
        }

        if (File.Exists(Path.Combine(appDirectory, "mix.lock")))
        {
            build.Copy("mix.lock", "./");
        }

        if (Directory.Exists(Path.Combine(appDirectory, "config")))
        {
            // `mix deps.compile` reads config/config.exs, so the configuration must arrive before it runs.
            build.Copy("config", "config");
        }

        if (File.Exists(Path.Combine(appDirectory, "mix.exs")))
        {
            // Without mix.exs there is no dependency list to read, so the step would only fail later.
            build.Run("mix deps.get --only prod && mix deps.compile");
        }

        build
            .Copy(".", ".")
            .Run("mix compile");

        if (hasAssetPackages)
        {
            // esbuild and tailwind reach npm through the assets directory. `npm ci` needs the lock file,
            // which the build context carries.
            build.Run("npm ci --prefix assets");
        }

        if (hasAssets)
        {
            // `mix assets.deploy` builds and digests the static files that the release serves.
            build.Run("mix assets.deploy");
        }

        build.Run($"mix release {ShellQuote(releaseName)}");

        // Intermediate FROM stages for the resources that supply container files.
        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var runtime = WriteRuntimeStage(context, runtimeImage, logger);

        runtime.CopyFrom(
            "build",
            $"{ContainerAppDirectory}/_build/prod/rel/{releaseName}",
            "./",
            $"{NonRootUser}:{NonRootUser}");

        // The release reads MIX_ENV at boot to select its runtime configuration.
        runtime.Env("MIX_ENV", "prod");

        if (isPhoenix)
        {
            // PHX_SERVER tells the release to start the endpoint. Without it the release boots the
            // application but serves nothing.
            runtime.Env("PHX_SERVER", "true");
        }

        runtime
            .User(NonRootUser)
            .Cmd([$"{ContainerAppDirectory}/bin/{releaseName}", "start"]);
    }

    /// <summary>
    /// Writes the single-stage Dockerfile for a release that Mix already built.
    /// </summary>
    /// <param name="releaseDirectory">The root directory of the release. It is also the build context.</param>
    /// <param name="releaseName">The release name, which names the launcher script.</param>
    /// <param name="context">The callback context that supplies the Dockerfile builder.</param>
    public static void WriteRelease(string releaseDirectory, string releaseName, DockerfileBuilderCallbackContext context)
    {
        var logger = context.Services.GetService<ILogger<MixReleaseResource>>();

        // A release directory holds no mix.exs, so the detector normally returns the default versions.
        // The OTP major version selects the runtime image, and the release carries its own runtime system.
        var versions = ElixirVersionDetector.Detect(releaseDirectory);
        var otpMajor = MajorVersion(versions.OtpVersion);

        context.Resource.TryGetLastAnnotation<DockerfileBaseImageAnnotation>(out var baseImageAnnotation);
        var runtimeImage = baseImageAnnotation?.RuntimeImage ?? RuntimeImage(otpMajor);

        WriteBuildContextIgnore(releaseDirectory, DefaultReleaseBuildContextIgnoreContent, context);

        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var runtime = WriteRuntimeStage(context, runtimeImage, logger);

        // The build context is the release directory itself, so the whole context becomes the image.
        runtime.Copy(".", "./", $"{NonRootUser}:{NonRootUser}");

        runtime
            .User(NonRootUser)
            .Cmd([$"{ContainerAppDirectory}/bin/{releaseName}", "start"]);
    }

    /// <summary>
    /// Writes the part of the runtime stage that both shapes share: packages, locale, the non-root
    /// account, the working directory, and the container files from other resources.
    /// </summary>
    private static DockerfileStage WriteRuntimeStage(
        DockerfileBuilderCallbackContext context,
        string runtimeImage,
        ILogger? logger)
    {
        var runtime = context.Builder.From(runtimeImage);

        if (IsAlpine(runtimeImage))
        {
            // A plain Alpine image holds none of the libraries that the Erlang runtime system links
            // against. musl images carry no locale support, so the locale steps are left out.
            runtime
                .Run("apk --no-cache add ca-certificates libstdc++ ncurses-libs openssl")
                .Run($"addgroup -S {NonRootUser} && adduser -S -G {NonRootUser} {NonRootUser}");
        }
        else
        {
            // The default image already holds OpenSSL, ncurses, and the C++ runtime, because it built
            // the Erlang runtime system against them. The certificates and the locale data are removed
            // from that image, and the release needs both.
            runtime
                .Run("apt-get update -y && apt-get install -y ca-certificates locales && apt-get clean && rm -f /var/lib/apt/lists/*_*")
                // The BEAM reads and writes UTF-8, so the image must have a UTF-8 locale.
                .Run("sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen")
                .Env("LANG", "en_US.UTF-8")
                .Env("LANGUAGE", "en_US:en")
                .Env("LC_ALL", "en_US.UTF-8")
                .Run($"groupadd --system --gid 999 {NonRootUser} && useradd --system --gid 999 --uid 999 --no-create-home {NonRootUser}");
        }

        runtime
            .WorkDir(ContainerAppDirectory)
            .AddContainerFiles(context.Resource, ContainerAppDirectory, logger);

        return runtime;
    }

    /// <summary>
    /// Adds the default <c>.dockerignore</c> rules to the build annotation.
    /// </summary>
    /// <remarks>
    /// A <c>&lt;dockerfile&gt;.dockerignore</c> replaces the <c>.dockerignore</c> of the context root
    /// instead of merging with it, so an authored file wins and Aspire adds nothing.
    /// </remarks>
    private static void WriteBuildContextIgnore(string contextDirectory, string content, DockerfileBuilderCallbackContext context)
    {
        if (context.Resource.TryGetLastAnnotation<DockerfileBuildAnnotation>(out var buildAnnotation)
            && !File.Exists(Path.Combine(contextDirectory, ".dockerignore")))
        {
            buildAnnotation.BuildContextIgnoreContent ??= content;
        }
    }

    /// <summary>
    /// Selects the release name for an application.
    /// </summary>
    /// <remarks>
    /// <c>WithReleaseName</c> wins. Without it the name comes from the <c>app:</c> key in
    /// <c>mix.exs</c>, which is the name that <c>mix release</c> uses by default. The last fallback is
    /// the resource name with each hyphen replaced, because a release name is an Erlang atom and a
    /// resource name can hold a hyphen.
    /// </remarks>
    internal static string ResolveReleaseName(IResource resource, string appDirectory)
    {
        if (resource.TryGetLastAnnotation<ElixirReleaseNameAnnotation>(out var annotation))
        {
            return annotation.ReleaseName;
        }

        if (TryReadMixAppName(appDirectory, out var appName))
        {
            return appName;
        }

        return resource.Name.Replace('-', '_');
    }

    private static bool TryReadMixAppName(string appDirectory, out string appName)
    {
        appName = string.Empty;

        var mixExsPath = Path.Combine(appDirectory, "mix.exs");
        if (!File.Exists(mixExsPath))
        {
            return false;
        }

        foreach (var line in File.ReadLines(mixExsPath))
        {
            var match = MixAppNameRegex().Match(line);
            if (match.Success)
            {
                appName = match.Groups["app"].Value;
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Returns the major part of a version, for example <c>28</c> from <c>28.4.1</c>.
    /// </summary>
    private static string MajorVersion(string version)
    {
        var separator = version.IndexOf('.');
        return separator < 0 ? version : version[..separator];
    }

    private static bool IsAlpine(string image)
        => image.Contains("alpine", StringComparison.OrdinalIgnoreCase)
        || image.Contains("musl", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Wraps <paramref name="value"/> in POSIX single quotes, so the shell of a <c>RUN</c> statement
    /// reads every metacharacter as a literal. An embedded single quote uses the standard POSIX
    /// technique: <c>'</c> becomes <c>'\''</c>.
    /// </summary>
    private static string ShellQuote(string value) =>
        $"'{value.Replace("'", "'\\''")}'";

    // Matches: app: :my_app
    [GeneratedRegex(@"app:\s*:(?<app>[a-z_0-9]+)")]
    private static partial Regex MixAppNameRegex();
}
