// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable ASPIREDOCKERFILEBUILDER001

using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Aspire.Hosting.Dart;

/// <summary>
/// Generates the Dockerfile that <c>aspire publish</c> writes for a Dart application.
/// </summary>
/// <remarks>
/// <para>
/// Every shape gets two stages. The build stage starts from the official <c>dart</c> image, because
/// every shape needs the Dart SDK and the pub dependencies. A static site can name a different build
/// image, and <c>WithDockerfileBaseImage</c> replaces the image of either stage.
/// </para>
/// <para>
/// The runtime stage follows the output of the build. An application that compiles to a native
/// executable runs from an empty image with the Dart runtime libraries only. An application that
/// builds a directory of static files runs from an Nginx image, because no Dart process is left.
/// </para>
/// </remarks>
internal static class DartDockerfileGenerator
{
    /// <summary>The working directory in both stages.</summary>
    private const string ContainerAppDirectory = "/app";

    /// <summary>The path of the executable that <c>dart compile exe</c> writes.</summary>
    private const string CompiledExecutablePath = $"{ContainerAppDirectory}/bin/server";

    /// <summary>The empty base image that carries the Dart runtime libraries only.</summary>
    internal const string ScratchImage = "scratch";

    /// <summary>The directory that Nginx sends to the browser.</summary>
    private const string NginxRootDirectory = "/usr/share/nginx/html";

    /// <summary>The Nginx configuration file that the default image reads.</summary>
    private const string NginxConfigPath = "/etc/nginx/conf.d/default.conf";

    /// <summary>The port that the default Nginx image binds.</summary>
    internal const int NginxPort = 80;

    /// <summary>The directory that holds the executables of the activated pub packages.</summary>
    private const string PubCacheBinDirectory = "/root/.pub-cache/bin";

    // Without these rules `COPY . .` uploads the package cache and the build output to the daemon.
    // Both are large, and both are rebuilt inside the image, so both must stay out of the context.
    // See https://docs.docker.com/build/concepts/context/#dockerignore-files.
    private const string DefaultBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to take over these rules.
        .dart_tool
        build
        .packages
        node_modules
        **/node_modules
        .git
        .gitignore
        .DS_Store
        .env
        .env.*
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    /// <summary>
    /// Builds the default build-stage image reference.
    /// </summary>
    /// <remarks>
    /// The official <c>dart</c> image carries the SDK and a <c>/runtime</c> directory that holds the
    /// libraries that a compiled executable needs. Use the <c>buildImage</c> parameter of
    /// <c>WithStaticSiteBuild</c>, or <c>WithDockerfileBaseImage</c>, to select a different image,
    /// for example an image that also carries Flutter.
    /// </remarks>
    internal static string BuildImage(string dartVersion)
        => $"docker.io/library/dart:{dartVersion}";

    /// <summary>
    /// Builds the default runtime-stage image reference for a directory of static files.
    /// </summary>
    internal static string StaticSiteRuntimeImage() => "docker.io/library/nginx:alpine";

    /// <summary>
    /// Writes the Dockerfile for a Dart application.
    /// </summary>
    /// <param name="appDirectory">The directory that holds <c>pubspec.yaml</c>. It is also the build context.</param>
    /// <param name="context">The callback context that supplies the Dockerfile builder.</param>
    public static void Write(string appDirectory, DockerfileBuilderCallbackContext context)
    {
        ArgumentException.ThrowIfNullOrEmpty(appDirectory);
        ArgumentNullException.ThrowIfNull(context);

        var logger = context.Services.GetService<ILogger<DartAppResource>>();
        var version = DartVersionDetector.Detect(appDirectory);

        // ctx.Resource is the container resource that PublishAsDockerFile substitutes in. It shares
        // the annotation collection of the Dart resource, so annotations that the developer applied
        // to the Dart resource are visible here.
        context.Resource.TryGetLastAnnotation<DockerfileBaseImageAnnotation>(out var baseImage);

        WriteBuildContextIgnore(appDirectory, context);

        var isStaticSite = context.Resource.TryGetLastAnnotation<DartStaticSiteBuildAnnotation>(out var staticSite);

        // WithDockerfileBaseImage is the general override of both stage images, so it wins over the
        // build image of the static-site shape, which in turn wins over the official dart image.
        var buildImage = baseImage?.BuildImage ?? staticSite?.BuildImage ?? BuildImage(version.Version);

        var build = context.Builder.From(buildImage, "build");

        WriteDependencyStage(appDirectory, build);

        if (isStaticSite)
        {
            WriteFrameworkBuild(context.Resource, build, staticSite!.Command, staticSite.Args);

            context.Builder.AddContainerFilesStages(context.Resource, logger);
            WriteStaticSiteRuntimeStage(context, baseImage?.RuntimeImage ?? StaticSiteRuntimeImage(), staticSite, logger);
            return;
        }

        if (context.Resource.TryGetLastAnnotation<DartCompiledBuildAnnotation>(out var compiledBuild))
        {
            WriteFrameworkBuild(context.Resource, build, compiledBuild.Command, compiledBuild.Args);

            context.Builder.AddContainerFilesStages(context.Resource, logger);

            // The executable reads its browser bundle from the directory that holds it, so the image
            // gets the complete output directory and not the executable alone.
            var runtime = WriteExecutableRuntimeStage(context, baseImage?.RuntimeImage ?? ScratchImage, logger);
            runtime.CopyFrom(
                "build",
                $"{ContainerAppDirectory}/{compiledBuild.OutputDirectory}/",
                $"{ContainerAppDirectory}/");

            WriteRuntimeArgsAndEnvironment(
                context.Resource,
                runtime,
                $"{ContainerAppDirectory}/{compiledBuild.Executable}");
            return;
        }

        // The default shape: `dart compile exe` writes one self-contained executable.
        var entrypoint = DartPublishEntrypointAnnotation.Resolve(context.Resource);
        build.Run($"dart compile exe {ShellQuoteIfNeeded(entrypoint)} -o {CompiledExecutablePath}");

        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var executableRuntime = WriteExecutableRuntimeStage(context, baseImage?.RuntimeImage ?? ScratchImage, logger);
        executableRuntime.CopyFrom("build", CompiledExecutablePath, $"{ContainerAppDirectory}/bin/");

        WriteRuntimeArgsAndEnvironment(context.Resource, executableRuntime, CompiledExecutablePath);
    }

    /// <summary>
    /// Writes the part of the build stage that resolves the pub dependencies.
    /// </summary>
    /// <remarks>
    /// The manifest changes less often than the source, so it is copied first. That keeps the
    /// dependency layer in the cache across source edits. The second <c>dart pub get</c> reads the
    /// cache only, so it adds the packages that the complete source needs without a network call.
    /// </remarks>
    private static void WriteDependencyStage(string appDirectory, DockerfileStage build)
    {
        build.WorkDir(ContainerAppDirectory);

        var hasPubspec = File.Exists(Path.Combine(appDirectory, "pubspec.yaml"));

        if (hasPubspec)
        {
            // The pattern also carries pubspec.lock and pubspec_overrides.yaml when they exist.
            build.Copy("pubspec.*", "./");
            build.Run("dart pub get");
        }

        build.Copy(".", ".");

        if (hasPubspec)
        {
            build.Run("dart pub get --offline");
        }
    }

    /// <summary>
    /// Writes the build steps of a framework command: the optional pub package, the search path, and
    /// the command itself.
    /// </summary>
    private static void WriteFrameworkBuild(IResource resource, DockerfileStage build, string command, string[] args)
    {
        if (resource.TryGetLastAnnotation<DartPublishToolAnnotation>(out var tool))
        {
            build.Run($"dart pub global activate {ShellQuoteIfNeeded(tool.Package)}");

            // `dart pub global activate` writes the executables here. The official image already has
            // the directory on the search path, but a different build image does not.
            build.Env("PATH", $"{PubCacheBinDirectory}:$PATH");
        }

        var commandLine = string.Join(' ', new[] { command }.Concat(args).Select(ShellQuoteIfNeeded));
        build.Run(commandLine);
    }

    /// <summary>
    /// Writes the runtime stage of an application that compiled to a native executable.
    /// </summary>
    private static DockerfileStage WriteExecutableRuntimeStage(
        DockerfileBuilderCallbackContext context,
        string runtimeImage,
        ILogger? logger)
    {
        var runtime = context.Builder.From(runtimeImage);

        if (string.Equals(runtimeImage, ScratchImage, StringComparison.Ordinal))
        {
            // An empty image holds no C library and no loader, so the executable cannot start. The
            // official dart image builds /runtime for this step. See
            // https://github.com/dart-lang/dart-docker.
            runtime.CopyFrom("build", "/runtime/", "/");
        }

        runtime.WorkDir(ContainerAppDirectory);
        runtime.AddContainerFiles(context.Resource, ContainerAppDirectory, logger);

        return runtime;
    }

    /// <summary>
    /// Writes the environment variables and the <c>CMD</c> statement of a runtime stage.
    /// </summary>
    private static void WriteRuntimeArgsAndEnvironment(
        IResource resource,
        DockerfileStage runtime,
        string executablePath)
    {
        var runtimeContext = new DartPublishRuntimeContext();

        if (resource.TryGetLastAnnotation<DartPublishRuntimeAnnotation>(out var annotation))
        {
            annotation.Configure(resource, runtimeContext);
        }

        foreach (var variable in runtimeContext.EnvironmentVariables)
        {
            runtime.Env(variable.Key, variable.Value);
        }

        runtime.Cmd([executablePath, .. runtimeContext.Args]);
    }

    /// <summary>
    /// Writes the runtime stage of an application that built a directory of static files.
    /// </summary>
    private static void WriteStaticSiteRuntimeStage(
        DockerfileBuilderCallbackContext context,
        string runtimeImage,
        DartStaticSiteBuildAnnotation staticSite,
        ILogger? logger)
    {
        var runtime = context.Builder.From(runtimeImage);

        runtime.CopyFrom("build", $"{ContainerAppDirectory}/{staticSite.OutputDirectory}", NginxRootDirectory);

        if (staticSite.SpaFallback)
        {
            // A single-page application owns its routes in the browser, so every path that names no
            // file must return the one page. The single quotes stop the shell from reading $uri.
            var configuration = new[]
            {
                "server {",
                $"    listen {NginxPort};",
                "    server_name _;",
                $"    root {NginxRootDirectory};",
                "    index index.html;",
                "    location / {",
                "        try_files $uri $uri/ /index.html;",
                "    }",
                "}"
            };

            var lines = string.Join(' ', configuration.Select(ShellQuote));
            runtime.Run($"printf '%s\\n' {lines} > {NginxConfigPath}");
        }

        runtime.AddContainerFiles(context.Resource, NginxRootDirectory, logger);

        runtime.Expose(NginxPort);
    }

    /// <summary>
    /// Adds the default <c>.dockerignore</c> rules to the build annotation.
    /// </summary>
    /// <remarks>
    /// A <c>&lt;dockerfile&gt;.dockerignore</c> replaces the <c>.dockerignore</c> of the context root
    /// instead of merging with it, so an authored file wins and Aspire adds nothing.
    /// </remarks>
    private static void WriteBuildContextIgnore(string contextDirectory, DockerfileBuilderCallbackContext context)
    {
        if (context.Resource.TryGetLastAnnotation<DockerfileBuildAnnotation>(out var buildAnnotation)
            && !File.Exists(Path.Combine(contextDirectory, ".dockerignore")))
        {
            buildAnnotation.BuildContextIgnoreContent ??= DefaultBuildContextIgnoreContent;
        }
    }

    /// <summary>
    /// Wraps <paramref name="value"/> in POSIX single quotes, so the shell of a <c>RUN</c> statement
    /// reads every metacharacter as a literal. An embedded single quote uses the standard POSIX
    /// technique: <c>'</c> becomes <c>'\''</c>.
    /// </summary>
    private static string ShellQuote(string value) =>
        $"'{value.Replace("'", "'\\''")}'";

    /// <summary>
    /// Quotes <paramref name="value"/> only when the shell would read one of its characters as more
    /// than text.
    /// </summary>
    /// <remarks>
    /// A build command holds many ordinary words, and quotation marks around each one make the
    /// generated file hard to read. The safe set below holds no shell metacharacter, so a value that
    /// holds those characters only reaches the command unchanged. Every other value gets the quotes.
    /// </remarks>
    private static string ShellQuoteIfNeeded(string value)
    {
        if (value.Length > 0 && value.All(IsSafeShellCharacter))
        {
            return value;
        }

        return ShellQuote(value);
    }

    private static bool IsSafeShellCharacter(char character)
        => char.IsAsciiLetterOrDigit(character) || character is '.' or '_' or '/' or '-' or '=' or ':' or ',' or '+' or '@' or '%';
}
