//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class ElixirHostingExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Elixir.ElixirAppResource> AddElixirApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithAppArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, params object[] args)
            where T : Elixir.ElixirAppResource { throw null; }
    }
}

namespace Aspire.Hosting.Elixir
{
    [AspireExport(ExposeProperties = true)]
    public partial class ElixirAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public ElixirAppResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }
}