//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class ElixirHostingExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Elixir.ElixirAppResource> AddElixirApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Elixir.MixReleaseResource> AddMixRelease(this IDistributedApplicationBuilder builder, string name, string releaseDirectory, string? releaseName = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Elixir.PhoenixAppResource> AddPhoenixApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithAppArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, params object[] args)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport("withElixirEctoDatabase", MethodName = "withEctoDatabase")]
        public static ApplicationModel.IResourceBuilder<T> WithEctoDatabase<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.IResourceWithConnectionString> database)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithEctoMigrate<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithElixirErlOptions<T>(this ApplicationModel.IResourceBuilder<T> builder, string options)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithErlFlags<T>(this ApplicationModel.IResourceBuilder<T> builder, string flags)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMixCompile<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMixDeps<T>(this ApplicationModel.IResourceBuilder<T> builder, bool install = true)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMixEnv<T>(this ApplicationModel.IResourceBuilder<T> builder, string env)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMixTask<T>(this ApplicationModel.IResourceBuilder<T> builder, string task, params object[] args)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport("withElixirNodeName", MethodName = "withNodeName")]
        public static ApplicationModel.IResourceBuilder<T> WithNodeName<T>(this ApplicationModel.IResourceBuilder<T> builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? cookie = null)
            where T : Elixir.ElixirAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Elixir.PhoenixAppResource> WithPhoenixHealthCheck(this ApplicationModel.IResourceBuilder<Elixir.PhoenixAppResource> builder, string path = "/health") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithReleaseName<T>(this ApplicationModel.IResourceBuilder<T> builder, string name)
            where T : Elixir.ElixirAppResource { throw null; }
    }
}

namespace Aspire.Hosting.Elixir
{
    [AspireExport(ExposeProperties = true)]
    public partial class ElixirAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public ElixirAppResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class MixReleaseResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public MixReleaseResource(string name, string command, string releaseDirectory, string releaseName) : base(default!, default!, default!) { }

        public string ReleaseName { get { throw null; } }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class PhoenixAppResource : ElixirAppResource
    {
        public PhoenixAppResource(string name, string workingDirectory) : base(default!, default!) { }
    }
}